gRPC Server: Fix java.lang.NoClassDefFoundError for Log4j Logger
Explicitly add log4j-api and log4j-core modules as runtime dependencies when running via the main method of the OpenNLPGrpcServer class to resolve missing class error.

(cherry picked from commit 9a23c73df244a6cabb54ad13ab262c66f0324bca)